Lesson 6
ushakova/TestGuru pull request #5
Opened 2019-03-11 18:40 UTC by ushakova

2019-03-11 21:03 UTC, BubuntuClu requested changes

2019-03-11 21:03 UTC, BubuntuClu commented on app/models/answer.rb
> +  validate :number_of_answers
стоит делать эту проверку только при создании ответа

2019-03-11 21:03 UTC, BubuntuClu commented on app/models/test.rb
> -                    .order('tests.title DESC')
а куда сортировка ушла?

2019-03-11 21:03 UTC, BubuntuClu commented on app/models/test.rb
>      joins(:category).where(categories: { title: category_title })
это в скоуп по заданию надо вынести

2019-03-11 21:03 UTC, BubuntuClu commented on app/models/test.rb
> +  validates :level, numericality: { only_integer: true,
`Может существовать только один Тест с данным названием и уровнем` это в моделе тоже стоит указать, не только в БД

2019-03-12 07:25 UTC, ushakova commented on app/models/test.rb
> -                    .order('tests.title DESC')
и правда

2019-03-12 14:29 UTC, merged